const App = {
    data() {
        return {
            faculty: [
                {
                    "id": "CS03",
                    "img1": "../../images/faculty/CS03.jpg",
                    "img2": "../images/faculty/CS03.jpg",
                    "profile1": "../view-profile.html?CS03",
                    "profile2": "./view-profile.html?CS03",
                    "deptid": "CA",
                    "name": "Mr. Abdul Samad C.",
                    "desg": "Assistant Professor and Head",
                    "dept": "Computer Applications",
                },
                {
                    "id": "CS02",
                    "img1": "../../images/faculty/CS02.jpg",
                    "img2": "../images/faculty/CS02.jpg",
                    "profile1": "../view-profile.html?CS02",
                    "profile2": "./view-profile.html?CS02",
                    "deptid": "CSAI",
                    "name": "Mr. ARSHAD P.T.",
                    "desg": "Assistant Professor and Head",
                    "dept": "Computer Science & Artificial Intelligence",
                },
                {
                    "id": "CS07",
                    "img1": "../../images/faculty/CS07.jpg",
                    "img2": "../images/faculty/CS07.jpg",
                    "profile1": "../view-profile.html?CS07",
                    "profile2": "./view-profile.html?CS07",
                    "deptid": "CSAI",
                    "name": "Mr. Muhammed Haneesh K.P",
                    "desg": "Assistant Professor",
                    "dept": "Computer Science & Artificial Intelligence",
                },
                {
                    "id": "CS11",
                    "img1": "../../images/faculty/CS11.jpg",
                    "img2": "../images/faculty/CS11.jpg",
                    "profile1": "../view-profile.html?CS11",
                    "profile2": "./view-profile.html?CS11",
                    "deptid": "CSAI",
                    "name": "Ms. Divya M.C.",
                    "desg": "Assistant Professor",
                    "dept": "Computer Science & Artificial Intelligence",
                },
                {
                    "id": "CS13",
                    "img1": "../../images/faculty/CS13.jpg",
                    "img2": "../images/faculty/CS13.jpg",
                    "profile1": "../view-profile.html?CS13",
                    "profile2": "./view-profile.html?CS13",
                    "deptid": "CA",
                    "name": "Ms. Safeena C",
                    "desg": "Assistant Professor",
                    "dept": "Computer  Applications",
                },
                {
                    "id": "CS15",
                    "img1": "../../images/faculty/CS15.jpg",
                    "img2": "../images/faculty/CS15.jpg",
                    "profile1": "../view-profile.html?CS15",
                    "profile2": "./view-profile.html?CS15",
                    "deptid": "CA",
                    "name": "Mr. Anshid Babu T.M.",
                    "desg": "Assistant Professor",
                    "dept": "Computer Applications",
                },
                {
                    "id": "CS16",
                    "img1": "../../images/faculty/CS16.jpg",
                    "img2": "../images/faculty/CS16.jpg",
                    "profile1": "../view-profile.html?CS16",
                    "profile2": "./view-profile.html?CS16",
                    "deptid": "CA",
                    "name": "Ms. Rasheeja A.P.",
                    "desg": "Assistant Professor",
                    "dept": "Computer  Applications",
                },
                {
                    "id": "CS17",
                    "img1": "../../images/faculty/CS17.jpg",
                    "img2": "../images/faculty/CS17.jpg",
                    "profile1": "../view-profile.html?CS17",
                    "profile2": "./view-profile.html?CS17",
                    "deptid": "CSAI",
                    "name": "Ms. Fayida C.K.",
                    "desg": "Assistant Professor",
                    "dept": "Computer Science & Artificial Intelligence",
                },
                {
                    "id": "CS18",
                    "img1": "../../images/faculty/CS18.jpg",
                    "img2": "../images/faculty/CS18.jpg",
                    "profile1": "../view-profile.html?CS18",
                    "profile2": "./view-profile.html?CS18",
                    "deptid": "CA",
                    "name": "Ms. Raseena V.",
                    "desg": "Assistant Professor",
                    "dept": "Computer  Applications",
                },
                {
                    "id": "MT01",
                    "img1": "../../images/faculty/MT01.jpg",
                    "img2": "../images/faculty/MT01.jpg",
                    "profile1": "../view-profile.html?MT01",
                    "profile2": "./view-profile.html?MT01",
                    "deptid": "MAT",
                    "name": "Ms. Faseela V.",
                    "desg": "Assistant Professor and Head",
                    "dept": "Mathematics",
                },
                
                {
                    "id": "MT12",
                    "img1": "../../images/faculty/MT12.jpg",
                    "img2": "../images/faculty/MT12.jpg",
                    "profile1": "../view-profile.html?MT12",
                    "profile2": "./view-profile.html?MT12",
                    "deptid": "MAT",
                    "name": "Ms. Sneha  N P",
                    "desg": "Assistant Professor",
                    "dept": "Mathematics",
                },
                {
                    "id": "ST01",
                    "img1": "../../images/faculty/ST01.jpg",
                    "img2": "../images/faculty/ST01.jpg",
                    "profile1": "../view-profile.html?ST01",
                    "profile2": "./view-profile.html?ST01",
                    "deptid": "STAT",
                    "name": "Ms. Nazreen K.T. ",
                    "desg": "Assistant Professor and Head",
                    "dept": "Statistics",
                },
                {
                    "id": "ST02",
                    "img1": "../../images/faculty/ST02.jpg",
                    "img2": "../images/faculty/ST02.jpg",
                    "profile1": "../view-profile.html?ST02",
                    "profile2": "./view-profile.html?ST02",
                    "deptid": "STAT",
                    "name": "Ms. Radhika P.K.",
                    "desg": "Assistant Professor",
                    "dept": "Statistics",
                },
                {
                    "id": "CM14",
                    "img1": "../../images/faculty/CM14.jpg",
                    "img2": "../images/faculty/CM14.jpg",
                    "profile1": "../view-profile.html?CM14",
                    "profile2": "./view-profile.html?CM14",
                    "deptid": "COM",
                    "name": "Mr. A.K. Shanawas",
                    "desg": "Assistant Professor and Head",
                    "dept": "Commerce",
                },
               
                {
                    "id": "CM25",
                    "img1": "../../images/faculty/CM25.jpg",
                    "img2": "../images/faculty/CM25.jpg",
                    "profile1": "../view-profile.html?CM25",
                    "profile2": "./view-profile.html?CM25",
                    "deptid": "COM",
                    "name": "Dr. Haris M.",
                    "desg": "Assistant Professor",
                    "dept": "Commerce",
                },

                {
                    "id": "CM28",
                    "img1": "../../images/faculty/CM28.jpg",
                    "img2": "../images/faculty/CM28.jpg",
                    "profile1": "../view-profile.html?CM28",
                    "profile2": "./view-profile.html?CM28",
                    "deptid": "COM",
                    "name": "Mr. Prajeesh Thazhathedath",
                    "desg": "Assistant Professor",
                    "dept": "Commerce",
                },
               
                {
                    "id": "MS05",
                    "img1": "../../images/faculty/MS05.jpg",
                    "img2": "../images/faculty/MS05.jpg",
                    "profile1": "../view-profile.html?MS05",
                    "profile2": "./view-profile.html?MS05",
                    "deptid": "COM",
                    "name": "Ms. Safa Hanan C.K.",
                    "desg": "Assistant Professor",
                    "dept": "Commerce"
                },
                {
                    "id": "CM33",
                    "img1": "../../images/faculty/CM33.jpg",
                    "img2": "../images/faculty/CM33.jpg",
                    "profile1": "../view-profile.html?CM33",
                    "profile2": "./view-profile.html?CM33",
                    "deptid": "COM",
                    "name": "Mr. Muhammed Rizwan N.K.",
                    "desg": "Assistant Professor",
                    "dept": "Commerce",
                },
                {
                    "id": "CM32",
                    "img1": "../../images/faculty/CM32.jpg",
                    "img2": "../images/faculty/CM32.jpg",
                    "profile1": "../view-profile.html?CM32",
                    "profile2": "./view-profile.html?CM32",
                    "deptid": "COM",
                    "name": "Mr. Vasil",
                    "desg": "Assistant Professor",
                    "dept": "Commerce",
                },
                {
                    "id": "BT03",
                    "img1": "../../images/faculty/BT03.jpg",
                    "img2": "../images/faculty/BT03.jpg",
                    "profile1": "../view-profile.html?BT03",
                    "profile2": "./view-profile.html?BT03",
                    "deptid": "BT",
                    "name": "Dr. Sahaya Shibu B.",
                    "desg": "Assistant Professor and Head",
                    "dept": "Biotechnology",
                },
                {
                    "id": "BT02",
                    "img1": "../../images/faculty/BT02.jpg",
                    "img2": "../images/faculty/BT02.jpg",
                    "profile1": "../view-profile.html?BT02",
                    "profile2": "./view-profile.html?BT02",
                    "deptid": "BT",
                    "name": "Dr. Servin Wesley",
                    "desg": "Assistant Professor",
                    "dept": "Biotechnology",
                },
                {
                    "id": "BT07",
                    "img1": "../../images/faculty/BT07.jpg",
                    "img2": "../images/faculty/BT07.jpg",
                    "profile1": "../view-profile.html?BT07",
                    "profile2": "./view-profile.html?BT07",
                    "deptid": "BT",
                    "name": "Ms. Nafila P.P.",
                    "desg": "Assistant Professor",
                    "dept": "Biotechnology",
                },
                {
                    "id": "BT13",
                    "img1": "../../images/faculty/BT13.jpg",
                    "img2": "../images/faculty/BT13.jpg",
                    "profile1": "../view-profile.html?BT13",
                    "profile2": "./view-profile.html?BT13",
                    "deptid": "BT",
                    "name": "Ms. Akhila P.K.",
                    "desg": "Assistant Professor",
                    "dept": "Biotechnology",
                },
                {
                    "id": "BT15",
                    "img1": "../../images/faculty/BT15.jpg",
                    "img2": "../images/faculty/BT15.jpg",
                    "profile1": "../view-profile.html?BT15",
                    "profile2": "./view-profile.html?BT15",
                    "deptid": "BT",
                    "name": "Dr. Deepa",
                    "desg": "Assistant Professor",
                    "dept": "Biotechnology",
                },
                {
                    "id": "BC01",
                    "img1": "../../images/faculty/BC01.jpg",
                    "img2": "../images/faculty/BC01.jpg",
                    "profile1": "../view-profile.html?BC01",
                    "profile2": "./view-profile.html?BC01",
                    "deptid": "BC",
                    "name": "Dr. Shonima Govindan",
                    "desg": "Assistant Professor and Head",
                    "dept": "Biochemistry",
                },
                {
                    "id": "BC02",
                    "img1": "../../images/faculty/BC02.jpg",
                    "img2": "../images/faculty/BC02.jpg",
                    "profile1": "../view-profile.html?BC02",
                    "profile2": "./view-profile.html?BC02",
                    "deptid": "BC",
                    "name": "Ms. Anjana M.",
                    "desg": "Assistant Professor",
                    "dept": "Biochemistry",
                },

                {
                    "id": "EC08",
                    "img1": "../../images/faculty/EC08.jpg",
                    "img2": "../images/faculty/EC08.jpg",
                    "profile1": "../view-profile.html?EC08",
                    "profile2": "./view-profile.html?EC08",
                    "deptid": "ECO",
                    "name": "Lt. Lukmanul Hakeem M",
                    "desg": "Assistant Professor and Head",
                    "dept": "Economics",
                },
                {
                    "id": "EC11",
                    "img1": "../../images/faculty/EC11.jpg",
                    "img2": "../images/faculty/EC11.jpg",
                    "profile1": "../view-profile.html?EC11",
                    "profile2": "./view-profile.html?EC11",
                    "deptid": "ECO",
                    "name": "Ms. Zanoobiya",
                    "desg": "Assistant Professor",
                    "dept": "Economics",
                },

                {
                    "id": "EC12",
                    "img1": "../../images/faculty/EC12.jpg",
                    "img2": "../images/faculty/EC12.jpg",
                    "profile1": "../view-profile.html?EC12",
                    "profile2": "./view-profile.html?EC12",
                    "deptid": "ECO",
                    "name": "Ms. Thahsin V.K",
                    "desg": "Assistant Professor",
                    "dept": "Economics",
                },
                {
                    "id": "EN12",
                    "img1": "../../images/faculty/EN12.jpg",
                    "img2": "../images/faculty/EN12.jpg",
                    "profile1": "../view-profile.html?EN12",
                    "profile2": "./view-profile.html?EN12",
                    "deptid": "ENG",
                    "name": "Dr. Najda A",
                    "desg": "Assistant Professor and Head",
                    "dept": "English",
                },
                {
                    "id": "EN07",
                    "img1": "../../images/faculty/EN07.jpg",
                    "img2": "../images/faculty/EN07.jpg",
                    "profile1": "../view-profile.html?EN07",
                    "profile2": "./view-profile.html?EN07",
                    "deptid": "ENG",
                    "name": "Mr. Sreekumar P.",
                    "desg": "Assistant Professor",
                    "dept": "English",
                },
               

                {
                    "id": "EN14",
                    "img1": "../../images/faculty/EN14.jpg",
                    "img2": "../images/faculty/EN14.jpg",
                    "profile1": "../view-profile.html?EN14",
                    "profile2": "./view-profile.html?EN14",
                    "deptid": "ENG",
                    "name": "Ms. Jouhara K P",
                    "desg": "Assistant Professor",
                    "dept": "English",
                },
                {
                    "id": "EN19",
                    "img1": "../../images/faculty/EN19.jpg",
                    "img2": "../images/faculty/EN19.jpg",
                    "profile1": "../view-profile.html?EN19",
                    "profile2": "./view-profile.html?EN19",
                    "deptid": "ENG",
                    "name": "Ms. Raheena P.",
                    "desg": "Assistant Professor",
                    "dept": "English",
                },
                {
                    "id": "EN23",
                    "img1": "../../images/faculty/EN23.jpg",
                    "img2": "../images/faculty/EN23.jpg",
                    "profile1": "../view-profile.html?EN23",
                    "profile2": "./view-profile.html?EN23",
                    "deptid": "ENG",
                    "name": "Ms. Aysha Muradh",
                    "desg": "Assistant Professor",
                    "dept": "English",
                },
                {
                    "id": "EN26",
                    "img1": "../../images/faculty/EN26.jpg",
                    "img2": "../images/faculty/EN26.jpg",
                    "profile1": "../view-profile.html?EN26",
                    "profile2": "./view-profile.html?EN26",
                    "deptid": "ENG",
                    "name": "Ms. Nilofer",
                    "desg": "Assistant Professor",
                    "dept": "English",
                },
                
            
                {
                    "id": "EN29",
                    "img1": "../../images/faculty/EN29.jpg",
                    "img2": "../images/faculty/EN29.jpg",
                    "profile1": "../view-profile.html?EN29",
                    "profile2": "./view-profile.html?EN29",
                    "deptid": "ENG",
                    "name": "Ms. Zayana P.K.",
                    "desg": "Assistant Professor",
                    "dept": "English",
                },
                {
                    "id": "CH03",
                    "img1": "../../images/faculty/CH03.jpg",
                    "img2": "../images/faculty/CH03.jpg",
                    "profile1": "../view-profile.html?CH03",
                    "profile2": "./view-profile.html?CH03",
                    "deptid": "CHE",
                    "name": "Mr. Vaisakh Kuzhveetil",
                    "desg": "Assistant Professor and Head",
                    "dept": "Chemistry",
                },
                {
                    "id": "CH04",
                    "img1": "../../images/faculty/CH04.jpg",
                    "img2": "../images/faculty/CH04.jpg",
                    "profile1": "../view-profile.html?CH04",
                    "profile2": "./view-profile.html?CH04",
                    "deptid": "CHE",
                    "name": "Mr. Rahul P",
                    "desg": "Assistant Professor",
                    "dept": "Chemistry",
                },
                {
                    "id": "FT02",
                    "img1": "../../images/faculty/FT02.jpg",
                    "img2": "../images/faculty/FT02.jpg",
                    "profile1": "../view-profile.html?FT02",
                    "profile2": "./view-profile.html?FT02",
                    "deptid": "FT",
                    "name": "Ms. Sujitha A.P.",
                    "desg": "Assistant Professor and Head",
                    "dept": "Food Technology"
                },
                {
                    "id": "FT15",
                    "img1": "../../images/faculty/FT15.jpg",
                    "img2": "../images/faculty/FT15.jpg",
                    "profile1": "../view-profile.html?FT15",
                    "profile2": "./view-profile.html?FT15",
                    "deptid": "FT",
                    "name": "Ms. K. Noorjahan",
                    "desg": "Assistant Professor",
                    "dept": "Food Technology"
                },

                {
                    "id": "FT19",
                    "img1": "../../images/faculty/FT19.jpg",
                    "img2": "../images/faculty/FT19.jpg",
                    "profile1": "../view-profile.html?FT19",
                    "profile2": "./view-profile.html?FT19",
                    "deptid": "FT",
                    "name": "Ms. Aiswarya P.M.",
                    "desg": "Assistant Professor",
                    "dept": "Food Technology"
                },
                {
                    "id": "FT20",
                    "img1": "../../images/faculty/FT20.jpg",
                    "img2": "../images/faculty/FT20.jpg",
                    "profile1": "../view-profile.html?FT20",
                    "profile2": "./view-profile.html?FT20",
                    "deptid": "FT",
                    "name": "Ms. Shabna P.T.",
                    "desg": "Assistant Professor",
                    "dept": "Food Technology"
                },

                {
                    "id": "FT22",
                    "img1": "../../images/faculty/FT22.jpg",
                    "img2": "../images/faculty/FT22.jpg",
                    "profile1": "../view-profile.html?FT22",
                    "profile2": "./view-profile.html?FT22",
                    "deptid": "FT",
                    "name": "Dr. Anusha R.",
                    "desg": "Assistant Professor",
                    "dept": "Food Technology"
                },
                {
                    "id": "CM21",
                    "img1": "../../images/faculty/CM21.jpg",
                    "img2": "../images/faculty/CM21.jpg",
                    "profile1": "../view-profile.html?CM21",
                    "profile2": "./view-profile.html?CM21",
                    "deptid": "IF",
                    "name": "Mr. Abdul Majeed K.",
                    "desg": "Assistant Professor and Head",
                    "dept": "Islamic Finance",
                },


                {
                    "id": "CM27",
                    "img1": "../../images/faculty/CM27.jpg",
                    "img2": "../images/faculty/CM27.jpg",
                    "profile1": "../view-profile.html?CM27",
                    "profile2": "./view-profile.html?CM27",
                    "deptid": "IF",
                    "name": "Ms. Muneera D.N.",
                    "desg": "Assistant Professor",
                    "dept": "Islamic Finance",
                },
                
                {
                    "id": "IF05",
                    "img1": "../../images/faculty/IF05.jpg",
                    "img2": "../images/faculty/IF05.jpg",
                    "profile1": "../view-profile.html?IF05",
                    "profile2": "./view-profile.html?IF05",
                    "deptid": "IF",
                    "name": "Mr. Shaheer Anaz T V",
                    "desg": "Assistant Professor",
                    "dept": "Islamic Finance"
                },
                {
                    "id": "CM31",
                    "img1": "../../images/faculty/CM31.jpg",
                    "img2": "../images/faculty/CM31.jpg",
                    "profile1": "../view-profile.html?CM31",
                    "profile2": "./view-profile.html?CM31",
                    "deptid": "IF",
                    "name": "Ms. Shahina P.C.",
                    "desg": "Assistant Professor",
                    "dept": "Islamic FInance",
                },
                {
                    "id": "IS05",
                    "img1": "../../images/faculty/IS05.jpg",
                    "img2": "../images/faculty/IS05.jpg",
                    "profile1": "../view-profile.html?IS05",
                    "profile2": "./view-profile.html?IS05",
                    "deptid": "IS",
                    "name": "Dr. Shebeeb Khan P.",
                    "desg": "Assistant Professor and Head",
                    "dept": "Islamic Studies"
                },
                {
                    "id": "IS02",
                    "img1": "../../images/faculty/IS02.jpg",
                    "img2": "../images/faculty/IS02.jpg",
                    "profile1": "../view-profile.html?IS02",
                    "profile2": "./view-profile.html?IS02",
                    "deptid": "IS",
                    "name": "Dr. Hassan Shareef K.P.",
                    "desg": "Assistant Professor ",
                    "dept": "Islamic Studies"
                },

                {
                    "id": "IS07",
                    "img1": "../../images/faculty/IS07.jpg",
                    "img2": "../images/faculty/IS07.jpg",
                    "profile1": "../view-profile.html?IS07",
                    "profile2": "./view-profile.html?IS07",
                    "deptid": "IS",
                    "name": "Ms. Semiya P.M.",
                    "desg": "Assistant Professor",
                    "dept": "Islamic Studies"
                },
                {
                    "id": "ML02",
                    "img1": "../../images/faculty/ML02.jpg",
                    "img2": "../images/faculty/ML02.jpg",
                    "profile1": "../view-profile.html?ML02",
                    "profile2": "./view-profile.html?ML02",
                    "deptid": "MAL",
                    "name": "Mr. Bineesh M.K.",
                    "desg": "Assistant Professor and Head",
                    "dept": "Malayalam"
                },
                {
                    "id": "MB03",
                    "img1": "../../images/faculty/MB03.jpg",
                    "img2": "../images/faculty/MB03.jpg",
                    "profile1": "../view-profile.html?MB03",
                    "profile2": "./view-profile.html?MB03",
                    "deptid": "MB",
                    "name": "Ms. Farha Baramy ",
                    "desg": "Assistant Professor and Head",
                    "dept": "Microbiology"
                },
                {
                    "id": "MB01",
                    "img1": "../../images/faculty/MB01.jpg",
                    "img2": "../images/faculty/MB01.jpg",
                    "profile1": "../view-profile.html?MB01",
                    "profile2": "./view-profile.html?MB01",
                    "deptid": "MB",
                    "name": "Dr. Shainy N.K. ",
                    "desg": "Assistant Professor",
                    "dept": "Microbiology"
                },
                {
                    "id": "MB05",
                    "img1": "../../images/faculty/MB05.jpg",
                    "img2": "../images/faculty/MB05.jpg",
                    "profile1": "../view-profile.html?MB05",
                    "profile2": "./view-profile.html?MB05",
                    "deptid": "MB",
                    "name": "Dr. Smitha K.V.",
                    "desg": "Assistant Professor",
                    "dept": "Microbiology"
                },
                {
                    "id": "MB02",
                    "img1": "../../images/faculty/MB02.jpg",
                    "img2": "../images/faculty/MB02.jpg",
                    "profile1": "../view-profile.html?MB02",
                    "profile2": "./view-profile.html?MB02",
                    "deptid": "MB",
                    "name": "Dr. Asha B. ",
                    "desg": "Assistant Professor",
                    "dept": "Microbiology"
                },


                {
                    "id": "MB06",
                    "img1": "../../images/faculty/MB06.jpg",
                    "img2": "../images/faculty/MB06.jpg",
                    "profile1": "../view-profile.html?MB06",
                    "profile2": "./view-profile.html?MB06",
                    "deptid": "MB",
                    "name": "Dr. Shabanamol S.",
                    "desg": "Assistant Professor",
                    "dept": "Microbiology"
                },
                {
                    "id": "MB07",
                    "img1": "../../images/faculty/MB07.jpg",
                    "img2": "../images/faculty/MB07.jpg",
                    "profile1": "../view-profile.html?MB07",
                    "profile2": "./view-profile.html?MB07",
                    "deptid": "MB",
                    "name": "Ms. Aswathi A.",
                    "desg": "Assistant Professor",
                    "dept": "Microbiology"
                },
               
                
                {
                    "id": "PS06",
                    "img1": "../../images/faculty/PS06.jpg",
                    "img2": "../images/faculty/PS06.jpg",
                    "profile1": "../view-profile.html?PS06",
                    "profile2": "./view-profile.html?PS06",
                    "deptid": "PSY",
                    "name": "Ms. Raniya P.",
                    "desg": "Assistant Professor",
                    "dept": "Psychology"
                },
                {
                    "id": "PS07",
                    "img1": "../../images/faculty/PS07.jpg",
                    "img2": "../images/faculty/PS07.jpg",
                    "profile1": "../view-profile.html?PS07",
                    "profile2": "./view-profile.html?PS07",
                    "deptid": "PSY",
                    "name": "Ms. Devika M.S.",
                    "desg": "Assistant Professor",
                    "dept": "Psychology"
                },
                {
                    "id": "PS10",
                    "img1": "../../images/faculty/PS10.jpg",
                    "img2": "../images/faculty/PS10.jpg",
                    "profile1": "../view-profile.html?PS10",
                    "profile2": "./view-profile.html?PS10",
                    "deptid": "PSY",
                    "name": "Ms. Akshara",
                    "desg": "Assistant Professor",
                    "dept": "Psychology"
                },
                {
                    "id": "PS11",
                    "img1": "../../images/faculty/PS11.jpg",
                    "img2": "../images/faculty/PS11.jpg",
                    "profile1": "../view-profile.html?PS11",
                    "profile2": "./view-profile.html?PS11",
                    "deptid": "PSY",
                    "name": "Ms. Sandra P.",
                    "desg": "Assistant Professor",
                    "dept": "Psychology"
                },
                {
                    "id": "PS12",
                    "img1": "../../images/faculty/PS12.jpg",
                    "img2": "../images/faculty/PS12.jpg",
                    "profile1": "../view-profile.html?PS12",
                    "profile2": "./view-profile.html?PS12",
                    "deptid": "PSY",
                    "name": "Ms. Anjali M.",
                    "desg": "Assistant Professor",
                    "dept": "Psychology"
                },
                
                {
                    "id": "MS01",
                    "img1": "../../images/faculty/MS01.jpg",
                    "img2": "../images/faculty/MS01.jpg",
                    "profile1": "../view-profile.html?MS01",
                    "profile2": "./view-profile.html?MS01",
                    "deptid": "MS",
                    "name": "Mr. Samsheer Babu M.",
                    "desg": "Assistant Professor and Head",
                    "dept": "Management Studies"
                },
                {
                    "id": "MS02",
                    "img1": "../../images/faculty/MS02.jpg",
                    "img2": "../images/faculty/MS02.jpg",
                    "profile1": "../view-profile.html?MS02",
                    "profile2": "./view-profile.html?MS02",
                    "deptid": "MS",
                    "name": "Mr. Mujeeb Rahiman Kattali",
                    "desg": "Assistant Professor",
                    "dept": "Management Studies"
                },
                {
                    "id": "MS04",
                    "img1": "../../images/faculty/MS04.jpg",
                    "img2": "../images/faculty/MS04.jpg",
                    "profile1": "../view-profile.html?MS04",
                    "profile2": "./view-profile.html?MS04",
                    "deptid": "MS",
                    "name": "Ms. Shana Wahab",
                    "desg": "Assistant Professor",
                    "dept": "Management Studies"
                },

                {
                    "id": "MS03",
                    "img1": "../../images/faculty/MS03.jpg",
                    "img2": "../images/faculty/MS03.jpg",
                    "profile1": "../view-profile.html?MS03",
                    "profile2": "./view-profile.html?MS03",
                    "deptid": "MS",
                    "name": "Ms. Haneesamol P.",
                    "desg": "Assistant Professor",
                    "dept": "Management Studies"
                },


                {
                    "id": "PE02",
                    "img1": "../../images/faculty/PE02.jpg",
                    "img2": "../images/faculty/PE02.jpg",
                    "profile1": "../view-profile.html?PE02",
                    "profile2": "./view-profile.html?PE02",
                    "deptid": "PE",
                    "name": "Mr. Sarath Krishna",
                    "desg": "Assistant Professor and Head",
                    "dept": "Physical Educaiton"
                },

                {
                    "id": "PH04",
                    "img1": "../../images/faculty/PH04.jpg",
                    "img2": "../images/faculty/PH04.jpg",
                    "profile1": "../view-profile.html?PH04",
                    "profile2": "./view-profile.html?PH04",
                    "deptid": "PHY",
                    "name": "Dr. Hajara. K.",
                    "desg": "Assistant Professor and Head",
                    "dept": "Physics"
                },
                {
                    "id": "PH09",
                    "img1": "../../images/faculty/PH09.jpg",
                    "img2": "../images/faculty/PH09.jpg",
                    "profile1": "../view-profile.html?PH09",
                    "profile2": "./view-profile.html?PH09",
                    "deptid": "PHY",
                    "name": "Dr. Raseel Rahman M.K.",
                    "desg": "Assistant Professor ",
                    "dept": "Physics"
                },
                {
                    "id": "BI01",
                    "img1": "../../images/faculty/BI01.jpg",
                    "img2": "../images/faculty/BI01.jpg",
                    "profile1": "../view-profile.html?BI01",
                    "profile2": "./view-profile.html?BI01",
                    "deptid": "BI",
                    "name": "Dr. Sahila M.M.",
                    "desg": "Assistant Professor and Head",
                    "dept": "Bioinformatics"
                },
                {
                    "id": "JM02",
                    "img1": "../../images/faculty/JM02.jpg",
                    "img2": "../images/faculty/JM02.jpg",
                    "profile1": "../view-profile.html?JM02",
                    "profile2": "./view-profile.html?JM02",
                    "deptid": "JMC",
                    "name": "Mr. Jamsheel C.",
                    "desg": "Assistant Professor and Head",
                    "dept": "Journalism & Mass Communication"
                },
                {
                    "id": "JM01",
                    "img1": "../../images/faculty/JM01.jpg",
                    "img2": "../images/faculty/JM01.jpg",
                    "profile1": "../view-profile.html?JM01",
                    "profile2": "./view-profile.html?JM01",
                    "deptid": "JMC",
                    "name": "Mr. Nasarullah P",
                    "desg": "Assistant Professor",
                    "dept": "Journalism & Mass Communication"
                },
                {
                    "id": "JM03",
                    "img1": "../../images/faculty/JM03.jpg",
                    "img2": "../images/faculty/JM03.jpg",
                    "profile1": "../view-profile.html?JM03",
                    "profile2": "./view-profile.html?JM03",
                    "deptid": "JMC",
                    "name": "Mr. Akhilnath K.S.",
                    "desg": "Assistant Professor",
                    "dept": "Journalism & Mass Communication"
                },
                {
                    "id": "HS01",
                    "img1": "../../images/faculty/HS01.jpg",
                    "img2": "../images/faculty/HS01.jpg",
                    "profile1": "../view-profile.html?HS01",
                    "profile2": "./view-profile.html?HS01",
                    "deptid": "HIS",
                    "name": "Mr. Muhammed Kamil T.P.",
                    "desg": "Assistant Professor and Vice Principal",
                    "dept": "History"
                },
                {
                    "id": "HS02",
                    "img1": "../../images/faculty/HS02.jpg",
                    "img2": "../images/faculty/HS02.jpg",
                    "profile1": "../view-profile.html?HS02",
                    "profile2": "./view-profile.html?HS02",
                    "deptid": "HIS",
                    "name": "Mr. Saidalavi K.M.",
                    "desg": "Assistant Professor ",
                    "dept": "History"
                },
                {
                    "id": "HN01",
                    "img1": "../../images/faculty/HN01.jpg",
                    "img2": "../images/faculty/HN01.jpg",
                    "profile1": "../view-profile.html?HN01",
                    "profile2": "./view-profile.html?HN01",
                    "deptid": "HND",
                    "name": "Dr. Sreevidya P V",
                    "desg": "Assistant Professor and Head",
                    "dept": "Hindi"
                },
                {
                    "id": "PA01",
                    "img1": "../../images/faculty/PA01.jpg",
                    "img2": "../images/faculty/PA01.jpg",
                    "profile1": "#",
                    "profile2": "#",
                    "deptid": "PA",
                    "name": "Ms. AMRUTHA K .N.",
                    "desg": "Assistant Professor and Head",
                    "dept": "Public Administration"
                },
                {
                    "id": "MSW01",
                    "img1": "../../images/faculty/MSW01.jpg",
                    "img2": "../images/faculty/MSW01.jpg",
                    "profile1": "../view-profile.html?MSW01",
                    "profile2": "./view-profile.html?MSW01",
                    "deptid": "MSW",
                    "name": "Dr. Noorunnida M. (Ph.D)",
                    "desg": "Assistant Professor and Head",
                    "dept": "Social Work"
                },
                {
                    "id": "MSW02",
                    "img1": "../../images/faculty/MSW02.jpg",
                    "img2": "../images/faculty/MSW02.jpg",
                    "profile1": "../view-profile.html?MSW02",
                    "profile2": "./view-profile.html?MSW02",
                    "deptid": "MSW",
                    "name": "Mr. Muhammed Shalikh N.",
                    "desg": "Assistant Professor",
                    "dept": "Social Work"
                },
                {
                    "id": "ARB04",
                    "img1": "../../images/faculty/ARB04.jpg",
                    "img2": "../images/faculty/ARB04.jpg",
                    "profile1": "../view-profile.html?ARB04",
                    "profile2": "./view-profile.html?ARB04",
                    "deptid": "ARB",
                    "name": "Mr. Abdulla Shihab P.M.",
                    "desg": "Assistant Professor and Head",
                    "dept": "Arabic"
                },
                {
                    "id": "ARB05",
                    "img1": "../../images/faculty/ARB05.jpg",
                    "img2": "../images/faculty/ARB05.jpg",
                    "profile1": "../view-profile.html?ARB05",
                    "profile2": "./view-profile.html?ARB05",
                    "deptid": "ARB",
                    "name": "Mr. Faizal A.",
                    "desg": "Assistant Professor ",
                    "dept": "Arabic"
                },
                {
                    "id": "MM01",
                    "img1": "../../images/faculty/MM01.jpg",
                    "img2": "../images/faculty/MM01.jpg",
                    "profile1": "../view-profile.html?MM01",
                    "profile2": "./view-profile.html?MM01",
                    "deptid": "MM",
                    "name": "Mr. Muhammed Abdul Rauf K.T.",
                    "desg": "Assistant Professor and Head",
                    "dept": "Multimedia"
                },
            ],
            IF: [],
            IS: [],
            BT: [],
            BC: [],
            CHE: [],
            COM: [],
            CA: [],
            CSAI:[],
            ECO: [],
            ENG: [],
            FT: [],
            MB: [],
            MAT: [],
            STAT: [],
            MAL: [],
            PSY: [],
            PHY: [],
            MS: [],
            JMC: [],
            PE: [],
            ARB: [],
            HIS: [],
            BI: [],
            HND: [],
            PA: [],
            MSW:[],
            MM:[]

        }
    },
    methods: {
        sortFaculty() {

            this.BT = this.faculty.filter((f) => f.deptid == 'BT')
            this.BC = this.faculty.filter((f) => f.deptid == 'BC')
            this.CHE = this.faculty.filter((f) => f.deptid == 'CHE')
            this.COM = this.faculty.filter((f) => f.deptid == 'COM')
            this.CA = this.faculty.filter((f) => f.deptid == 'CA')
            this.CSAI = this.faculty.filter((f) => f.deptid == 'CSAI')
            this.ECO = this.faculty.filter((f) => f.deptid == 'ECO')
            this.ENG = this.faculty.filter((f) => f.deptid == 'ENG')
            this.FT = this.faculty.filter((f) => f.deptid == 'FT')
            this.IF = this.faculty.filter((f) => f.deptid == 'IF')
            this.IS = this.faculty.filter((f) => f.deptid == 'IS')
            this.MB = this.faculty.filter((f) => f.deptid == 'MB')
            this.MAT = this.faculty.filter((f) => f.deptid == 'MAT')
            this.STAT = this.faculty.filter((f) => f.deptid == 'STAT')
            this.MAL = this.faculty.filter((f) => f.deptid == 'MAL')
            this.PSY = this.faculty.filter((f) => f.deptid == 'PSY')
            this.PHY = this.faculty.filter((f) => f.deptid == 'PHY')
            this.MS = this.faculty.filter((f) => f.deptid == 'MS')
            this.JMC = this.faculty.filter((f) => f.deptid == 'JMC')
            this.PE = this.faculty.filter((f) => f.deptid == 'PE')
            this.ARB = this.faculty.filter((f) => f.deptid == 'ARB')
            this.HIS = this.faculty.filter((f) => f.deptid == 'HIS')
            this.BI = this.faculty.filter((f) => f.deptid == 'BI')
            this.HND = this.faculty.filter((f) => f.deptid == 'HND')
            this.PA = this.faculty.filter((f) => f.deptid == 'PA')
            this.MSW = this.faculty.filter((f) => f.deptid == 'MSW')
            this.MM = this.faculty.filter((f) => f.deptid == 'MM')

        }
    },
    mounted() {
        this.sortFaculty()
    }
}

Vue.createApp(App).mount('#page-content')